### ISSUE TITLE
Error message error

### ISSUE THREAD

**Issue by tebb** [russellromney/brain-plasma#24]
![takes 1 pos arg](https://user-images.githubusercontent.com/15068043/95004695-91b35c80-05e6-11eb-9ed3-bdbb41e2986f.jpg)

![takes 1 pos arg - example 2](https://user-images.githubusercontent.com/15068043/95004770-a8a67e80-05e7-11eb-81ea-0be7680cb53f.jpg)

Hi Russell.

Should this be 0 and 1, 1 and 2 arguments?

If this is relatively simple to fix, please point me to the file and I'll have a go.  I tried searching the repo for parts of the error messages.

Howard

**Comment by russellromney** [comment]
The shown numbers are correct. Python class methods take `self` as the first positional argument so you can access class attributes and methods within the function.

```python
class Me:
    def name(self):
        return "Russell"
```

So if I pass an argument, it will get `self` and that argument which is 2 when it's expecting one:

![image](https://user-images.githubusercontent.com/22407809/96349481-990e4780-1075-11eb-98e3-28181234824c.png)

**Comment by tebb** [comment]
Hi Russell.

Thanks for taking the time to explain that.

**Comment by russellromney** [comment]
No problem, I'm glad there wasn't a problem with the code. Happy coding
